### ISSUE TITLE
Usuario se puede registrar pero este queda automaticamente activado

### ISSUE THREAD

**Issue by m-barrien** [m-barrien/usmbiolab#2]
Se necesita hacer un portal para que el admin pueda validar la cuenta antes de que el usuario pueda acceder a la intranet

**Comment by mlacasia** [comment]
Hice el link exclusivo para admin, ahora trabajo en hacer la lita desplegable.

**Comment by m-barrien** [comment]
la lista esta lista para ser desplegada pero falta que el metodo de controlador entregue las instancias de usuarios

**Comment by mlacasia** [comment]
Arreglado
